version: "3"

networks:
  luna:
    driver: bridge

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGNAME=postgres
      - PGUSER=cagatay
      - PGPASSWORD=Cagatay66.
      - PGPORT=5432
    networks:
      - luna

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: cagatay
      POSTGRES_PASSWORD: Cagatay66.
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - luna

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - luna

volumes:
  postgres_data:
