POST http://127.0.0.1:8000/authentication/login
Content-Type: application/json

{"email": "geezus@gmail.com", "password": "password"}

###
POST http://127.0.0.1:8000/authentication/signup
Content-Type: application/json

{ "password": "password", "email": "jkhgy@gmail.com", "user_type":"1", "first_name": "Geetansh", "last_name":"Des"}

###
GET http://127.0.0.1:8000/authentication/test_token
Content-Type: application/json 
Authorization: token fb0317b64d6997f718dc7fbcb076fd829f878e89
