# Generated by Django 4.2.5 on 2024-04-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0029_alter_module_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="Results",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("smoothed_output", models.JSONField()),
                ("raw_output", models.JSONField()),
                ("SurveyNumber_T", models.IntegerField()),
                ("time_evaluated", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.studentuser",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.studentsurvey",
                    ),
                ),
            ],
        ),
    ]
