# Generated by Django 4.2.5 on 2024-04-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0037_alter_studentsurvey_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Results",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("SurveyNumber_T", models.IntegerField(null=True)),
                ("time_evaluated", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("smoothed_output", models.FloatField(blank=True, null=True)),
                ("covariance_matrix", models.FloatField(blank=True, null=True)),
                ("smooth_covariance_matrix", models.FloatField(blank=True, null=True)),
                ("raw_output", models.FloatField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.module",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.studentuser",
                    ),
                ),
            ],
        ),
    ]
