# Generated by Django 4.2.5 on 2024-05-22 10:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_remove_form_form_type"),
        ("modelling", "0003_drop_form_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormResults",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "results",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(blank=True, null=True), size=None
                    ),
                ),
                (
                    "student_form",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.studentform",
                    ),
                ),
            ],
        ),
    ]
