# Generated by Django 4.2.5 on 2024-06-12 13:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelling", "0004_formresults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyresults",
            options={
                "verbose_name": "Modelling Result",
                "verbose_name_plural": "Modelling Results",
            },
        ),
        migrations.AlterField(
            model_name="formresults",
            name="results",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
    ]
