# Generated by Django 4.2.5 on 2024-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='inastructor',
            new_name='instructor',
        ),
        migrations.AlterField(
            model_name='form',
            name='form_type',
            field=models.CharField(choices=[('EQ', 'EQ'), ('IQ', 'IQ'), ('AIST', 'AIST')], default='EQ', max_length=50),
        ),
    ]
