# Generated by Django 4.2.5 on 2023-11-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='resolution',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('NOT_COMPLETED', 'Not Completed')], default='NOT_COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='abitur_note',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='main_language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('OTHER', 'Other')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Lecturer'), (3, 'Admin')], default=4),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.studentuser')),
            ],
        ),
    ]
