# Generated by Django 4.2.5 on 2023-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_form_resolution_alter_studentuser_abitur_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='main_language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('OTHER', 'Other')], null=True),
        ),
    ]
