# Generated by Django 4.2.5 on 2024-01-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_inastructor_module_instructor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('user', 'name')},
        ),
    ]
