# Generated by Django 4.2.5 on 2023-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_module_student_user_module_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='resource_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
