# Generated by Django 4.2.5 on 2023-12-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_module_resource_id_alter_module_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='student_user',
        ),
        migrations.AddField(
            model_name='module',
            name='instructor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentuser')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
