# Generated by Django 4.2.5 on 2024-01-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_module_institution_alter_module_owners_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
    ]
