# Generated by Django 4.2.5 on 2024-01-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_module_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('module_id', 'faculty')},
        ),
    ]
