# Generated by Django 4.2.5 on 2024-02-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_university_alter_module_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="form",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="form",
            name="created_by_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StudentSurveys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.JSONField(null=True)),
                (
                    "module_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.module"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.studentuser",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="form",
            name="resolution",
        ),
        migrations.RemoveField(
            model_name="form",
            name="user",
        ),
        migrations.CreateModel(
            name="StudentForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("NOT_COMPLETED", "Not Completed"),
                        ],
                        default="NOT_COMPLETED",
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(default=None, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.form"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.studentuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "form")},
            },
        ),
    ]
