# Generated by Django 4.2.5 on 2024-03-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_insert_initial_form_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.faculty",
            ),
        ),
    ]
