# Generated by Django 4.2.5 on 2024-03-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_module_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.faculty",
            ),
        ),
    ]
