# Generated by Django 4.2.5 on 2024-03-11 06:27

from django.db import migrations
from core.customFields import DayOfTheWeekField


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_module_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="survey_days",
            field=DayOfTheWeekField(null=True, blank=True),
        )
    ]
