# Generated by Django 4.2.5 on 2024-03-20 10:44

import core.customFields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_add_custom_module_dayfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="module",
            name="survey_days",
            field=core.customFields.DayOfTheWeekField(
                choices=[
                    ("1", "Monday"),
                    ("2", "Tuesday"),
                    ("3", "Wednesday"),
                    ("4", "Thursday"),
                    ("5", "Friday"),
                    ("6", "Saturday"),
                    ("7", "Sunday"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="StudentSurveys",
        ),
        migrations.AddField(
            model_name="studentsurvey",
            name="module_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.module"
            ),
        ),
        migrations.AddField(
            model_name="studentsurvey",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.studentuser"
            ),
        ),
    ]
