# Generated by Django 4.2.5 on 2024-03-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_rename_module_id_studentsurvey_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsurvey",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If set to False, the survey will not be visible to the student",
            ),
        ),
        migrations.AlterField(
            model_name="studentsurvey",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="studentsurvey",
            unique_together={("module", "is_active")},
        ),
    ]
