# Generated by Django 4.2.5 on 2024-03-25 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_rename_university_id_faculty_university_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
