# Generated by Django 4.2.5 on 2024-04-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_module_owners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="faculty",
        ),
        migrations.AddField(
            model_name="module",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[("WS", "Winter"), ("SS", "Summer")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.university",
            ),
        ),
    ]
