# Generated by Django 4.2.5 on 2024-04-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_module_code_alter_module_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.university"
            ),
        ),
    ]
