# Generated by Django 4.2.5 on 2024-04-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_module_university"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentsurvey",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="module",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="INACTIVE",
            ),
        ),
        migrations.AlterField(
            model_name="studentsurvey",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
