# Generated by Django 4.2.5 on 2024-04-04 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_alter_studentsurvey_unique_together_module_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsurvey",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="studentsurvey",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
