# Generated by Django 4.2.5 on 2024-04-04 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_studentsurvey_start_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentsurvey",
            unique_together={("student", "module")},
        ),
    ]
