# Generated by Django 4.2.5 on 2024-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_studentsurvey_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentsurvey",
            old_name="survey_status",
            new_name="resolution",
        ),
        migrations.AlterUniqueTogether(
            name="studentsurvey",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentsurvey",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("LATE", "Late"),
                    ("ARCHIVED", "ARCHIVED"),
                ],
                default="ACTIVE",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentmodule",
            unique_together={("module", "student")},
        ),
        migrations.RemoveField(
            model_name="studentsurvey",
            name="is_active",
        ),
    ]
