# Generated by Django 4.2.5 on 2024-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_rename_survey_status_studentsurvey_resolution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("LATE", "Late"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
            ),
        ),
    ]
