# Generated by Django 4.2.5 on 2024-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_studentsurvey_survey_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="survey_number",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
