# Generated by Django 4.2.5 on 2024-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_studentsurvey_survey_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsurvey",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
            ),
        ),
        migrations.AlterField(
            model_name="studentsurvey",
            name="survey_number",
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
