# Generated by Django 4.2.5 on 2024-05-21 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_studentsurvey_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="form_type",
        ),
    ]
