# Generated by Django 4.2.5 on 2024-06-12 13:19

import core.customFields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_auto_20240531_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="survey_days",
            field=core.customFields.DayOfTheWeekField(
                choices=[
                    ("1", "Monday"),
                    ("2", "Tuesday"),
                    ("3", "Wednesday"),
                    ("4", "Thursday"),
                    ("5", "Friday"),
                    ("6", "Saturday"),
                    ("7", "Sunday"),
                ],
                default="1",
                max_length=20,
                null=True,
            ),
        ),
    ]
