name: Trigger auto deployment for ca-luna-jotavkykpjya4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-luna-jotavkykpjya4-AutoDeployTrigger-d6ca3893-8a9a-4842-be03-52a6970d2006.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CALUNAJOTAVKYKPJYA4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CALUNAJOTAVKYKPJYA4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CALUNAJOTAVKYKPJYA4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: crjotavkykpjya4.azurecr.io
          registryUsername: ${{ secrets.CALUNAJOTAVKYKPJYA4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CALUNAJOTAVKYKPJYA4_REGISTRY_PASSWORD }}
          containerAppName: ca-luna-jotavkykpjya4
          resourceGroup: rg-luna_backend_dev
          imageToBuild: crjotavkykpjya4.azurecr.io/ca-luna-jotavkykpjya4:${{ github.sha }}
          


