# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Auto CI/CD - Build and deploy Luna to Azure

on:
  push:
    branches:
      - deploy-container-apps
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

<<<<<<< Updated upstream
    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5631949edefb4ca2a38f53559cf094b3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5a8c5245851944e2bfaa73f568401e5b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5631949edefb4ca2a38f53559cf094b3 }}/luna_backend-web:${{ github.sha }}
        file: ./Dockerfile
=======
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_c68fb7562b5e434188da46b9e0470064 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_ac3c51f2f9a140318df5dd752626a88b }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c68fb7562b5e434188da46b9e0470064 }}/luna_backend-web:${{ github.sha }}
          file: ./Dockerfile
>>>>>>> Stashed changes

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
<<<<<<< Updated upstream
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'luna-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_90912ee3ef1f40b097b612ab33288659 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5631949edefb4ca2a38f53559cf094b3 }}/luna_backend-web:${{ github.sha }}'
=======
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "luna-backend"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_586f3e50406247078ea197d115483829 }}
          images: "index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c68fb7562b5e434188da46b9e0470064 }}/luna_backend-web:${{ github.sha }}"
>>>>>>> Stashed changes
