name: Build and deploy container app to AWS EC2

on:
  push:
    branches:
      - deploy-container-apps
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/your_image_name:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Deploy to AWS EC2
        run: |
          # Install SSH client (if not already installed)
          sudo apt-get update
          sudo apt-get install -y openssh-client

          # SSH into the EC2 instance and execute Docker Compose commands
          ssh -o StrictHostKeyChecking=no ec2-user@52.5.114.46 \
          "cd /luna-backend && \
          docker-compose down && \
          docker-compose pull && \
          docker-compose up -d"
