name: Trigger auto deployment for luna-development

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ deploy-container-apps ]
    paths:
    - '**'
    - '.github/workflows/luna-development-AutoDeployTrigger-d0ada7fe-f4ce-43da-a6b5-bc27ab12b7bc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LUNADEVELOPMENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LUNADEVELOPMENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LUNADEVELOPMENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.LUNADEVELOPMENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LUNADEVELOPMENT_REGISTRY_PASSWORD }}
          containerAppName: luna-development
          resourceGroup: rg-luna-development
          imageToBuild: caodoe/luna-development:${{ github.sha }}
          


